import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { AcpSession } from '@process/acp/session/AcpSession';
import type { ClientFactory } from '@process/acp/infra/IAcpClient';
import type { AgentConfig, ProtocolHandlers, SessionCallbacks } from '@process/acp/types';

function createSession(cwd: string, additionalDirectories?: string[]): AcpSession {
  const config: AgentConfig = {
    agentBackend: 'hermes',
    agentSource: 'extension',
    agentId: 'lok-cli',
    cwd,
    additionalDirectories,
  };
  const callbacks: SessionCallbacks = {
    onMessage: vi.fn(),
    onSessionId: vi.fn(),
    onStatusChange: vi.fn(),
    onConfigUpdate: vi.fn(),
    onModelUpdate: vi.fn(),
    onModeUpdate: vi.fn(),
    onContextUsage: vi.fn(),
    onPermissionRequest: vi.fn(),
    onSignal: vi.fn(),
  };
  const clientFactory: ClientFactory = {
    create: vi.fn(() => {
      throw new Error('client factory should not be used by fs handler tests');
    }),
  };

  return new AcpSession(config, clientFactory, callbacks);
}

describe('AcpSession workspace fs handlers', () => {
  let tmpRoot: string;

  beforeEach(async () => {
    tmpRoot = await mkdtemp(path.join(os.tmpdir(), 'loksystem-acp-fs-'));
  });

  afterEach(async () => {
    await rm(tmpRoot, { recursive: true, force: true });
  });

  it('resolves relative read paths from the LokSystem workspace cwd', async () => {
    const workspace = path.join(tmpRoot, 'workspace');
    const filePath = path.join(workspace, 'docs', 'note.md');
    await mkdir(path.dirname(filePath), { recursive: true });
    await writeFile(filePath, 'hello from workspace', 'utf-8');

    const session = createSession(workspace);
    const handlers = (session as unknown as { buildProtocolHandlers: () => ProtocolHandlers }).buildProtocolHandlers();

    await expect(handlers.onReadTextFile({ path: 'docs/note.md' })).resolves.toEqual({
      content: 'hello from workspace',
    });
  });

  it('writes relative paths into the workspace and creates parent folders', async () => {
    const workspace = path.join(tmpRoot, 'workspace');
    const session = createSession(workspace);
    const handlers = (session as unknown as { buildProtocolHandlers: () => ProtocolHandlers }).buildProtocolHandlers();

    await handlers.onWriteTextFile({ path: 'reports/summary.md', content: 'generated by hermes' });

    await expect(readFile(path.join(workspace, 'reports', 'summary.md'), 'utf-8')).resolves.toBe(
      'generated by hermes'
    );
  });

  it('rejects traversal outside cwd while allowing configured additional directories', async () => {
    const workspace = path.join(tmpRoot, 'workspace');
    const shared = path.join(tmpRoot, 'shared');
    const session = createSession(workspace, [shared]);
    const handlers = (session as unknown as { buildProtocolHandlers: () => ProtocolHandlers }).buildProtocolHandlers();

    await expect(handlers.onWriteTextFile({ path: path.join(shared, 'ok.txt'), content: 'ok' })).resolves.toEqual({});
    await expect(handlers.onWriteTextFile({ path: '../escape.txt', content: 'no' })).rejects.toThrow(
      /outside permitted directories/
    );
  });
});
